### ISSUE TITLE
Multiple Ajax Calls

### ISSUE THREAD

**Issue by chriseling** [lognormal/boomerang#11]
Hello, I'm trying to use boomerang to also track timing for the ajax calls after page has loaded.  I have put the start_timer(t_done) call in jquery's beforeSend function and done() when the request is complete.

Is there a way for BOOMR to keep track of all the separate timers?  I noticed it won't send beacons for the ajax calls because the original onload timer has fired?

**Comment by bluesmoon** [comment]
Auto XHR instrumentation is now part of boomerang.
