### ISSUE TITLE
load timing for AJAX call

### ISSUE THREAD

**Issue by luckykurhe** [lognormal/boomerang#16]
Hi,
   I would like to fetch load timing for an AJAX call on my page.
   I am following steps @ http://lognormal.github.io/boomerang/doc/howtos/howto-2.html
   But while calling BOOMR.plugins.RT.startTimer("t_done"); 
   a. Do I need to send 2nd parameter as current time ? 
   b. Do I need to clear any timings for getting data for every AJAX call on page
   c. The scenario that have will trigger AJAX call after complete page is loaded.
       So can I just use BOOMR.plugins.RT.startTimer('t_page', timeInmilliseconds) again to get timing data for AJAX call. Or I will have to use "t_done" for AJAX calls? 
   Please suggest..

-lucky

**Comment by bluesmoon** [comment]
Auto XHR instrumentation is now part of boomerang
