### ISSUE TITLE
Recommended infrastructure 

### ISSUE THREAD

**Issue by Lazmonster** [lognormal/boomerang#23]
Hi I'd welcome some advice. We are new to Boomerang but are considering using it to monitor a client site with circa 82m Page Views per month traffic.
Do we need to supply our own infrastructure for data storage etc, or is there some out there for general use? If the latter, how is it paid for, and if the former grateful if somebody could recommend a spec for an environment to support this.
In other words, can we just deploy the tag and capture the results, or do we need to setup an infrastructure to do this?
By all means point me to any docs on the subject.
Many thanks

**Comment by nicjansma** [comment]
Since there aren't any open questions in this Issue, I'm going to close it for now.
