### ISSUE TITLE
Capture resource timing from inside iframes

### ISSUE THREAD

**Issue by bluesmoon** [lognormal/boomerang#29]
@philbooth this one is for you.

At the moment, ResourceTiming does not pull in anything from iframes since there's a different `window.performance` object in each iframe.  I think it would be cool if we could capture that within the restrictions of cross-domain checks.

IMO, we'd attempt to access the iframe's `documentElement` inside a `try/catch` block, and if successful, we'll pull the entire restiming object from there, and also the `window.performance.timing` object (for navigation timing).

**Comment by nicjansma** [comment]
Included in this change https://github.com/lognormal/boomerang/pull/68
