### ISSUE TITLE
Fire conversion event async

### ISSUE THREAD

**Issue by brianlmoon** [lognormal/boomerang#33]
Phillip and I talked today at Velocity about my use case for boomerang. I need to have a conversion event fired async that is not part of a separate page load. This is similar to Google Analytics event tracking. It is not associated with a new page within the session. Phillip said he thought he knew how to do this and was planning on working on the async code soon. I thought I would register an issue as a place for communication around the idea.

Thanks!

**Comment by nicjansma** [comment]
@brianlmoon - the SOASTA version of Boomerang should support this scenario with Custom Metrics on XHR beacons.  Contact us if you have any questions.
