### ISSUE TITLE
Frustrated beginner question

### ISSUE THREAD

**Issue by echomrg** [lognormal/boomerang#34]
Hi, i have a very basic problem i can't seem to get over with: i simply can get the library to work, even simply following the how to's.

I set up a simple page with just the `<script>` tag including the library, a very simple initialization and a console.log() instruction to test if the subscribed before_beacon works.

The plug seems to be correctly initialized (i can find the BOOMR object with firebug) but nothing happens when i load the page. 

the code is:
```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Boomerang testing</title>
	<script src="js/boomerang.js"></script>
</head>
<body>
<h1>Boomerang test</h1>
<div id="results"></div>
	<script type="text/javascript">
	BOOMR.init({
		user_ip: "<?php echo $_SERVER['REMOTE_ADDR'] ?>",
		beacon_url: "http://xxx.xxx.xxx.xxx/boomerang/images/beacon.gif",
		autorun: true
	});
	BOOMR.subscribe('before_beacon', function(o) {
		console.log("i'm doing stuff");
	});
	</script>
</body>
</html>
```

if i directly call the BOOMR.sendBeacon() method the subscribed event fires and the beacon get sent. otherwise nothing happens.

i tried putting the code both in the `<head>` tag and inside the `<body>` bit it makes no difference.

i'm testing the page from a XAMMP Apache webserver both with FF 30 and Chrome 35.

Any help would be really appreciated.
Thanks.
Marcello

**Comment by nicjansma** [comment]
Since this issue has been answered, and we haven't received any additional feedback, closing for now.
