### ISSUE TITLE
Huge jump in t_done median when moving to the latest boomerang version

### ISSUE THREAD

**Issue by glennslaven** [lognormal/boomerang#35]
I've been running with the boomerang script from this version (https://github.com/lognormal/boomerang/commit/035b7ea69157de6524acf019a04479eabaadf52c), and I recently updated to the latest (https://github.com/lognormal/boomerang/commit/1614c7b84856397b7dbeeca17021ea461fdd72a6).  I'm using the RT plugin.  Since doing that, the t_done measurements have jumped up, the median has gone from 2400ms to around 5000ms.  

You can see in the graph below, I turned it on for a few hours, then rolled back to the previous version.  Also you can see that the t_page and t_resp numbers don't move.
![t_done_jump](https://cloud.githubusercontent.com/assets/2200596/3639130/15c13774-106e-11e4-83a2-2c239f6e3e30.png)

Is this something I should have expected to happen?  Has their been a significant change in the way the t_done is calculated?  The only other change that I made when I upgraded was to stop using the navtiming plugin, I was using that before but not in version I deployed with the latest boomerang code.

**Comment by nicjansma** [comment]
Closing this as there hasn't been any activity for over a year.  Please re-open if you have additional details.
