### ISSUE TITLE
Tracking of user perceived response times

### ISSUE THREAD

**Issue by vlsi** [lognormal/boomerang#38]
I'm working on a performance of a web-based enterprise application and typical problem is to measure the time it takes to process button clicks.

The initial thought was "ok, I need to measure UI performance, then I use boomerang".
As I applied boomerang, it turned out to be something unrelated to performance validation.
None of the user clicks/actions result in just a page reload.

The issues (see below) can be solved to a certain degree with plugins, however it looks like blocking all the default boomerang beaconing behavior and rolling a new one.
I've been using `boomerang.js` for 2 months for measuring the response times, however I had to roll my own set of plugins.

Can you please clarify if you feel boomerang will/need/should support tracking of user perceived response times?

I understand that hosted applications and open-to-internet applications might have different requirements (e.g. in hosted enterprise app you have access.logs, thus you do not need resource timing beacons from client). However, it looks like current boomerang approach makes little sense for enterprise apps.

Here is the list of issues I ran into as I tried boomerang:
1) Boomerang is page-level based. For instance, it "does not work" for single-page applications when the page is loaded just once, and further actions are performed without page reloads.
I do not want per-ajax tracking (`RT.startTimer/done`). I want per end-user action tracking.
2) Boomerang does not glue multiple page transitions under a single "user activity". For instance, a single button click might perform some ajax calls, and then perform redirect to another page. Boomerang captures this redirect as a "new page".
3) Boomerang does not support frames/iframes. E.g. a click in main window might result in children iframe being created. I expect to get overall timing for the whole activity.
4) Boomerang does not track/capture page rendering activities. Big pages often take much time to process at javascript/css/html paints. If your SLAs are "4 seconds for full page render", you need take rendering into consideration and measure it.
5) Boomerang does not figure out the action user performs (e.g. the name of the button that was clicked, etc)

**Comment by nicjansma** [comment]
Thanks @vlsi for your feedback. Since there haven't been any additional comments on this issue, we're closing it for now.

Note SOASTA has contributed quite a bit of updates for monitoring SPAs in the `spa`, `angular` and other plugins. https://github.com/lognormal/boomerang/pull/68
