### ISSUE TITLE
Thoughts on a unit test suite?

### ISSUE THREAD

**Issue by philbooth** [lognormal/boomerang#40]
Discussion forked from https://github.com/bluesmoon/boomerang/pull/9.

@andreas-marschke [said](https://github.com/bluesmoon/boomerang/pull/9#issuecomment-59196665):

> I was thinking about unit-testing and best practices of implementing Unit-Tests in boomerang itself. I only hesitated yesterday to open up yet another issue just for an RFC on Unit-Testing or whats preferred by the users of Boomerang.
>
> What I can think of given that grunt has been integrated into boomerang on bluesmoon/boomerang I'd guess something like phantomjs or selenium and qunit or jasmine would be good.
>
> I worry however that not all parts of core boomerang.js can be tested this way as of now as they are not directly accessible. Splitting them up and building the closure for BOOMR upon calling grunt would be a good way forward.
>
> An added benefit would be a better separation of concerns inside boomerang to make it easier for newcomers to look at and understand the code instead of having to grok through a large monolithic file.
>
> Does anyone of the people subscribed or watching this repository have pointers or suggestions for a good javascript Unit-Testing Framework?
>
> What we'd also need is the abillity to unit-test all the plugins since they do most of the actual work in terms of gathering the data. Therefore having an extensible suite of Unit-Tests that can be extended towards plugins would be excellent.
>
> @bluesmoon If I understood your history correctly you should've worked at yahoo around the time NCZ was there. Anything regarding his work on maintainable Javascript in production that you can remember?
>
> By the way the book that came out of his experience at yahoo is a tremendous resource.
>
> DISCLAIMER: I'm not affiliated with O'Reilly, NCZ or any of the book publishing involved parties, I just thought it was a really good book.

**Comment by nicjansma** [comment]
We now have a fairly comprehensive (and updated for each new bug/feature) unit test suite via https://github.com/lognormal/boomerang/pull/68
