### ISSUE TITLE
RFC: Debug logging vs. Release no logging

### ISSUE THREAD

**Issue by andreas-marschke** [lognormal/boomerang#42]
Just a small question to you guys: 
Would it be okay to extend the Gruntfile to set 
```
BOOMR.util.log = function() {};
```
for the non-debug version while the debug version still has the logging intact as written in the source-code?

This would minimize logging on the console for the release versions of boomerang and still have debugging capabillities as desired when using the debug version.

Just my 2¢.

Thanks!

**Comment by nicjansma** [comment]
The latest `Gruntfile.js` builds both versions, where the debug keeps `BOOMR.log`.
