### ISSUE TITLE
2 Beacons sent yet one configured

### ISSUE THREAD

**Issue by andreas-marschke** [lognormal/boomerang#43]
Hi team!

I've recently set up another test-page with boomerang and came across a strange issue where 
boomerang would send a beacon when the side was loaded prior to anything else happening(ie. BW-Plugin run) and once afterwards basically giving me 2 beacons even though I had thought to have configured only one. The HTML is very basic:
```html
<html><head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <script type="text/javascript" src="/js/boomerang-0.9.0.js"></script>
  <script type="text/javascript">
    var u = ["//localhost:4001/", "54579344cbf7586a01f06d37/demo-webpage" + "/contact/start" ];
    BOOMR.init({
        beacon_url: u[0] + "beacon/" + u[1],
        BW: {
            base_url: u[0] ,
            cookie: "bandwidth",
            nruns: 1
        },
        RT: {}
    });
    BOOMR.addVar("plugins",Object.keys(BOOMR.plugins).join(","));

  </script>
  <link rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="/css/style.css">
  <script type="text/javascript">

  </script>

  <script type="text/javascript">

  </script>

</head>
<body>
<!-- Basic HTML -->
</body>
</html>
```
I have only added the script on top and `init()` configuration with some basic plugins (RT, BW ). But it would still send 2 beacons. A quick filter on url on my beacon-server: 
```text
"/beacon/54579344cbf7586a01f06d37/demo-webpage/shop/start"
"/image-l.gif?t=14157583130340.24289115308783948"
"/image-l.gif?t=14157583130590.3801573468372226"
"/image-l.gif?t=14157583131170.4063714947551489"
"/image-l.gif?t=14157583131730.46400602627545595"
"/image-l.gif?t=14157583132290.8678311358671635"
"/image-l.gif?t=14157583132840.9571576223243028"
"/image-l.gif?t=14157583133410.30458096507936716"
"/image-l.gif?t=14157583134090.8698015201371163"
"/image-l.gif?t=14157583134650.8809814790729433"
"/image-l.gif?t=14157583135200.416472946992144"
"/image-0.png?t=14157583135770.18505705893039703"
"/image-1.png?t=14157583136220.4129941747523844"
"/image-2.png?t=14157583136660.4191694213077426"
"/image-3.png?t=14157583136750.40637911669909954"
"/image-4.png?t=14157583136850.75371362012811"
"/image-5.png?t=14157583137000.6175008073914796"
"/image-6.png?t=14157583137630.6538159237243235"
"/beacon/54579344cbf7586a01f06d37/demo-webpage/contact/start"
```

The server it sends to is written by me (boomerang-express). And as far as I can see nothing should happen there even more strange the 2 requests have distinct request-ids meaning it must be something in the browser (tested with recent Chrome and Firefox). The setup is such that I have 2 express apps (boomerang-express + demo-web) both running on localhost (respectively localhost:4001 for b-e and localhost:4000 demo-web). They do not share any commonality between the 2 except that they are running on the same host machine. 

I've used a recent build from Git to do this test. I can not see that theres an extra eventListeners, however there has been a fired event from setImmediate when navigating away from the page. But why that fires I can not really tell.

Thanks in advance!

**Comment by vigneshshanmugam** [comment]
I am also seeing this issue,  

Metrics are collected on

+ On unload event (once refreshed - last collected value)
+ On load event

Need to dig in deeper to find whats causing this.

**Comment by bluesmoon** [comment]
This is by design.  We send one beacon on load and one beacon on unload.  The unload beacon has a marker called `rt.quit` to tell you it's an unload beacon.

**Comment by vigneshshanmugam** [comment]
Which value devs should consume to draw the metrics?. I am using resource timing plugin and I can see two objects having the ResTiming information. 

Does that mean, I should eliminate the first one since it is the last collected value and capture the second one?

**Comment by bluesmoon** [comment]
You should ignore all beacons with `rt.quit` on them.

**Comment by vigneshshanmugam** [comment]
@bluesmoon Alright Thanks :+1:
