### ISSUE TITLE
Ajax api call with relative url

### ISSUE THREAD

**Issue by cyang05** [lognormal/boomerang#45]
Boomerang is overriding url logic of jquery ajax call.
We use relative url to load static json file from the server with jquery ajax.
Let's say we have a json file with path:
http://www.example.com/json/my.json
var r_url = 'json/my.json'
$.ajax({
url: r_url,
type: "GET",
async: false,
timeout: 10000, // 10 seconds
success: function() {
},
error: function() {
});

Suppose current page is http://www.example.com/some/page
The actual url of the api becomes
http://www.example.com/some/page/json/my.json

We don't have this problem without boomerang library.
After investigating, we found that boomerang is making the ajax api call not jquery.
I think boomerang is overriding the relative url logic of jquery and cause the problem.

Thanks.

**Comment by bluesmoon** [comment]
Shouldn't `r_url` be set to `/json/my.json` to make it an absolute url?

**Comment by nicjansma** [comment]
@cyang05 I couldn't get your test case to work (without Boomerang):

Try this: http://dev.nicj.net/auto-xhr/

The page has your code, as above.  The URL it's passing to `$.ajax()` is `auto-xhr/test.json`, which you're saying should go to `http://dev.nicj.net/auto-xhr/test.json`.

I agree with Philip, that a relative URL without a leading slash such as `auto-xhr/test.json` would be relative to the current path `http://dev.nicj.net/auto-xhr`, and thus should be `http://dev.nicj.net/auto-xhr/auto-xhr/test.json`.

Is this only in a specific browser you're seeing this behavior?

What if you switch to a leading `/`?

**Comment by nicjansma** [comment]
@yang05 Are you by chance using an Angular app?  I may see an issue, where the "relative url" for an angular app is `/` while the method we use to cleanup the URL in `plugins/auto_xhr.js` might consider the history state URL (`/some/page`)

**Comment by cyang05** [comment]
We have a base tag inside our head element:
<base href="/">
I think all relative url should be relative to host root.

**Comment by cyang05** [comment]
And I think JQuery takes the base tag into consideration. I just tested your code with base tag, it worked.

**Comment by nicjansma** [comment]
@cyang05 I updated the repro at http://dev.nicj.net/auto-xhr, but I still can't seem to reproduce the problem.  Can you share the URL you're seeing the issue on?

**Comment by cyang05** [comment]
Someone loads this js file in our repo:
https://c.go-mpulse.net/boomerang/QB2NF-KYJFR-YPPM5-YJF6X-LAMRA
After comment it out, our website goes back to normal. The code was never in production. We found the problem on our local testing server.
Since boomerang is in that js file, we speculate it's caused by boomerang and apparently it's not.

Thanks for your time, I really appreciate it.

**Comment by bluesmoon** [comment]
It looks like you're using mPulse, which is the commercial service that uses boomerang.  The mPulse team is already in communication with your developers regarding this issue.

**Comment by nicjansma** [comment]
FYI, we have resolved this issue in mPulse and will be back-porting this to boomerang.js
