### ISSUE TITLE
Network infrastructure compresses images resulting in incorrect bandwidth calculation

### ISSUE THREAD

**Issue by paulcgt** [lognormal/boomerang#46]
Hi there,

I'm hosting Boomerang on a webserver that's fronted by a load balancer appliance. It appears as though the load balancer compresses images that the BW plugin downloads. 

Even though the cteonnt-length response header indicates that the content size is 4509613 bytes, Firebug reports that the amount of data downloaded to retrieve image-5.png is 1.5MB.

Cache-Control	private
Content-Encoding	gzip
Content-Type	text/plain
Date	Wed, 28 Jan 2015 10:11:52 GMT
Last-Modified	Thu, 11 Dec 2014 08:30:58 GMT
Transfer-Encoding	chunked
cteonnt-length	4509613
p3p	CP="NON CUR OTPi OUR NOR UNI"

While I could have our admins turn off compression, I'm concerned that another device in the chain may at some point in time be configured to compress images.

I've tried encrypting the image files with AES256 (because encrypted data isn't compressible, or, not much at any rate) but when I use Boomerang, I don't get any bandwidth measurement metrics. I've found that the browser console reports that variable t=null:

boomerang.bw: [debug] r=start=1422440260422
		end=1422440260433
		t=null
		state=false
		run=5,start=1422440260433
		end=1422440260443
		t=null
		state=false
		run=5,start=1422440260443
		end=1422440260458
		t=null

Do you perhaps have any thoughts or advice on this?

**Comment by nicjansma** [comment]
Hi Paul,

`t=null` is a consequence of `state=false`, which is set if an `onerror` was fired for that IMG.  Do you see any errors in your console or networking tab?  Can you set a breakpoint in the `onerror` to see what the error is?

**Comment by bluesmoon** [comment]
I bet the onerror fires because after encrypting the files they are no longer images and the browser's image parser is throwing the error.  What we'd need to do is create an incompressible image.  Anyone want to take a stab at that?

**Comment by paulcgt** [comment]
Thanks, you're both 100% correct. An error occurs when trying to load the encrypted data as an Image object. 

I've managed to create images containing random data and the results are pretty good, in that the Image object gets created and the band width calculation now looks correct.

The images seem to be slightly compressible, but negligibly so. I'll create the pull request later today or tomorrow for you to take a look.

Thanks for your help!

**Comment by bluesmoon** [comment]
Hey, thank you. It's obscure problems like this that we rely on the
community to find and fix. :)

**Comment by paulcgt** [comment]
Pleasure @bluesmoon - I've created the pull request. Hope it's all in order. :)

**Comment by bluesmoon** [comment]
Looks good, will merge shortly.
