### ISSUE TITLE
BW plugin never fires sendBeacon

### ISSUE THREAD

**Issue by tghamm** [lognormal/boomerang#49]
I've just started using boomerang, so apologies if I've simply missed something.  It looks like a commit in December 2014 removed the calls to sendBeacon in the BW plugin.  Because the plugin also returns a hard-coded true value to is_complete, I can't see how to either make it send a beacon when complete, or wait like the rest of the plugins do. 
Am I missing something?  Thanks!

**Comment by bluesmoon** [comment]
No, you're not missing anything.  This was deliberate, but probably misguided.  We should have made it a configurable setting, and that's what we'll do as a fix.

**Comment by tghamm** [comment]
Thank you for such a quick response. I wonder if this could possibly be configured to provide a callback when complete?  That would essentially allow it to be used ad-hoc (firing on run() and awaiting a completion callback).  It's not something I'd want fired on every page load anyways (necessarily), and I can see uses in a Single Page Application setting where it might be helpful to execute and await at arbitrary times. I can see why it was pulled out of the normal pipeline, it's a bit of a different beast than most of the other plugins.

If that's of interest, I'd be happy to take a crack at it.

**Comment by bluesmoon** [comment]
It will actually only run one every 7 days and store the result in a
cookie.

**Comment by tghamm** [comment]
Oh ok, that makes sense :).  I wanted to go ahead and get something working so I forked and added two params to allow bypass of the cookie cache, and to make the beacon wait. Hope it helps.

castle-it/boomerang@1b0c5a30f893774eb1597bd8e2b0a6c4165915d1

**Comment by tghamm** [comment]
If I updated documentation, would a PR be welcome?

**Comment by bluesmoon** [comment]
Added some code review comments to your code.  Yes, I'd accept a pull request with those fixed and the docs updated accordingly.  Thanks.

**Comment by tghamm** [comment]
Thanks!
Made the changes you requested (and thanks for the clarification on how that works). I also updated the documentation where applicable.  Let me know if there's anything you'd like me to change, and if not I'll send the request.

**Comment by bluesmoon** [comment]
Fixed by #50
