### ISSUE TITLE
Any plans of adding NPN/ALPN Negotiated Protocol on a page

### ISSUE THREAD

**Issue by vigneshshanmugam** [lognormal/boomerang#51]
Would be really helpful to draw metrics around the user base who are in HTTP/1.1 , SPDY and HTTP/2.

**Comment by bluesmoon** [comment]
At the moment only Chrome reports via JavaScript whether a page was loaded via SPDY or not, and we already collect that information.  No other browser exposes this information via JavaScript, so this request would have to go to the browser authors.

**Comment by vigneshshanmugam** [comment]
Thanks @bluesmoon
