### ISSUE TITLE
ESLint Default values resulting in errors on Build time

### ISSUE THREAD

**Issue by vigneshshanmugam** [lognormal/boomerang#52]
Lots of errors on building the plugin because of default ESLint rules like "no-multi-spaces", "comma-spacing". 

These rules should throw warnings rather than errors. 

Any thoughts?.

**Comment by andreas-marschke** [comment]
Maybe I'm too pedantic with this but I see this as a first sign in terms of the [broken window theory](http://en.wikipedia.org/wiki/Broken_windows_theory) (Short: Let one thing slide, the rest will follow and with it the demise of the project). I actually introduced a lot of the code changes (Grunt, testing, automation) to make it easier to check for such errors on a regular basis and plan to get this onto travis and track the progress with migrations towards a cleaner codebase. 

I'll give updates to these efforts in a bit.

@bluesmoon what do you think?

**Comment by bluesmoon** [comment]
We've selected the eslint rules to force what we want the project to be.  In particular, eslint failure needs to force the Makefile to fail so that subsequent rules aren't executed (for example if you have rules to push to your production server).

@andreas-marschke that's a good idea, but I'd speak to @nicjansma about the testing framework to use.

**Comment by vigneshshanmugam** [comment]
IMO, I do not want the build to fail even for a specific multi-space and comma-spacing issues. 

Would be better if we can throw warnings instead of errors. Can send a pull request if you are aligned.

**Comment by bluesmoon** [comment]
No, like I mentioned in the previous comment, I really do want the build to fail in these cases.  Coding style is very important and it's important to keep it clean.

**Comment by vigneshshanmugam** [comment]
Makes Sense. Check the errors that are thrown on the build time.

http://pastebin.com/6ykMbg4S

How do you want to proceed on this?.

**Comment by bluesmoon** [comment]
got it, looks like we're using different versions of eslint.

**Comment by vigneshshanmugam** [comment]
I am using version - 0.17.0

**Comment by bluesmoon** [comment]
Filed a bug on eslint: https://github.com/eslint/eslint/issues/2077

**Comment by vigneshshanmugam** [comment]
Awesome :+1:

**Comment by bluesmoon** [comment]
I've fixed any issues that needed fixing, and have made this one a warning
until eslint fixes it.

**Comment by vigneshshanmugam** [comment]
super cool :)
