### ISSUE TITLE
How to store the result in boomerang?

### ISSUE THREAD

**Issue by vijaykumarvemula** [lognormal/boomerang#55]
I am using boomerang.js to get the page loading time. The result displays on same page only. I want store that data in my salesforce. How to do this? How can i store the data using beacon url? How can i retrieve the stored data?

Here is my code
<apex:page controller="jstrackerexample">
  <html>
      <head><title>Boomerang Exp</title></head>
      <script src="/resource/1427268234000/boomeranexp"></script>
      <script type="text/javascript">
        BOOMR.init({
            beacon_url: "https://company-name.my.salesforce.com/resource/1427275857000/beaconresult",
            site_domain: "https://company-name.cs7.visual.force.com",
            user_ip: "203.129.222.211",
        });
        BOOMR.subscribe('before_beacon', function (o) {
            var html = "", t_name, t_other, others = [];
    
            if (!o.t_other) o.t_other = "";
    
            for (var k in o) {
                if (!k.match(/^(t_done|t_other|bw|lat|bw_err|lat_err|u|r2?)$/)) {
                    if (k.match(/^t_/)) {
                        o.t_other += "," + k + "|" + o[k];
                    }
                    else {
                        others.push(k + " = " + o[k]);
                    }
                }
            }
    
            if (o.t_done) { html += "This page took " + o.t_done + " ms to load<br>"; }
            if (o.t_other) {
                t_other = o.t_other.replace(/^,/, '').replace(/\|/g, ' = ').split(',');
                html += "Other timers measured: <br>";
                for (var i = 0; i < t_other.length; i++) {
                    html += "&nbsp;&nbsp;&nbsp;" + t_other[i] + " ms<br>";
                }
            }
            if (o.bw) { html += "Your bandwidth to this server is " + parseInt(o.bw * 8 / 1024) + "kbps (&#x00b1;" + parseInt(o.bw_err * 100 / o.bw) + "%)<br>"; }
            if (o.lat) { html += "Your latency to this server is " + parseInt(o.lat) + "&#x00b1;" + o.lat_err + "ms<br>"; }
    
            var r = document.getElementById('results');
            r.innerHTML = html;
    
            if (others.length) {
                r.innerHTML += "Other parameters:<br>";
    
                for (var i = 0; i < others.length; i++) {
                    var t = document.createTextNode(others[i]);
                    r.innerHTML += "&nbsp;&nbsp;&nbsp;";
                    r.appendChild(t);
                    r.innerHTML += "<br>";
    
                }
            }
         });
    </script>
    <script>
        function setVar(param){
            jQuery('[id$=myHiddenField]').val(param);
            passStringToController();
        }
    </script>
    <body>
        <h1>Boomerang Example:</h1>
        <p id="results">
        </p>
    </body>
  </html>
</apex:page>

result page is 

This page took 2100 ms to Load
Other timers measured: 
   boomerang = 2 ms
   boomr_fb = 1502 ms
   t_resp = 1382 ms
   t_page = 718 ms
Other parameters:
   rt.start = navigation
   rt.bstart = 1427350686076
   rt.end = 1427350686674

**Comment by bluesmoon** [comment]
I do not see any code attached.  I'm also not sure about how salesforce works, but in general, to store the beacon data you will need to write a piece of server side code using any server side language like php, java, node.js, ruby, etc.  This code would listen for HTTP requests and when a beacon comes in, it will parse it and write the results to a database.  You can then use SQL to query it.

Other people have used Google Analytics or Piwik to do the data storage.  There are also people who use a couchdb url as the beacon, so the data goes directly into couchdb.  Or you can use some of the freely available servers like https://github.com/nature/boomcatch or a commercial solution like the one from SOASTA's mPulse.

**Comment by tollmanz** [comment]
> Other people have used Google Analytics or Piwik to do the data storage.

Just lurking here...do you know of any documentation for using GA or Piwik for such storage? Thanks!

**Comment by bluesmoon** [comment]
I'd posted this to quora a while ago: http://www.quora.com/How-good-is-Yahoos-Boomerang-code-for-measuring-page-performance-Is-it-worth-the-integration-effort/answer/Philip-Tellis

If you don't have a quora account, these links will be useful:
https://gist.github.com/tmahesh/833066
http://benjamin-balet.info/developpement/performances/performance-ressentie-avec-piwik-et-boomerang/
http://www.slideshare.net/justindorfman/a-web-perf-dashboard-up-running-in-90-minutes-presentation
