### ISSUE TITLE
Beginners level question to ask?

### ISSUE THREAD

**Issue by turboTimo** [lognormal/boomerang#57]
I am new boomerang, looked at the relevant documents, found in very few examples online, my local build javaweb project to test the access path is local localhost, I want to know how to use a local project this javaweb boomerang, of course I do not have a dedicated server, only the local tomcat, ask specifically how to write the server and page? Can attach code to the best, really do not know how to start, thank you very much!

**Comment by bluesmoon** [comment]
Can't help you with writing a server, but if you already know how to write a Java servlet, then you can follow Howto-0 as an example of reading data from the beacon: http://www.lognormal.com/boomerang/doc/howtos/howto-0.html

You will need to translate the `extract_boomerang_data` from JavaScript to Java.

Your other option is to use something like https://github.com/nature/boomcatch which is an existing server for boomerang written in node.js.

**Comment by turboTimo** [comment]
After listening to your advice, I seem to have some ideas, very grateful!
