### ISSUE TITLE
Boomerang measurement of dynamic data

### ISSUE THREAD

**Issue by bcwood123** [lognormal/boomerang#60]
I am attempting to use Boomerang’s round trip page load timer, and it seems to work great for page-to-page transitions.  But for dynamic content, I am not getting good results.
 
I have a small part of the application that uses AngularJS, and inside the controller I have coded the following:
BOOMR.plugins.RT.startTimer("t_done");
// work… service calls via Ajax
BOOMR.plugins.RT.done();
 
 
And no beacon gets sent.  In fact, I can enter this code in the Javascript console, and nothing occurs either.  Any suggestions?

**Comment by cvazac** [comment]
like here (https://github.com/lognormal/boomerang/issues/38), try this:
var timer = window.BOOMR && BOOMR.requestStart("my_timer");
// work… service calls via Ajax
if (timer) timer.loaded();

**Comment by bcwood123** [comment]
This results in a beacon being sent which is incorrect - it starts from the previous page load, not the click.  It is similar to the rt.quit beacon.

**Comment by cvazac** [comment]
var timer = BOOMR.requestStart("my_timer");
setTimeout(function(){
  timer.loaded(); // `t_done` on the beacon that fires is ~1003 (ms)
}, 1000);

Are iframes involved?

**Comment by bcwood123** [comment]
You are correct.  My problem was I wasn't understanding when the Angular controller script was being executed.  So it had to do with the placement of the BOOM timer.  Thanks.
