### ISSUE TITLE
Bandwidth measurement of 0?

### ISSUE THREAD

**Issue by iamplo** [lognormal/boomerang#62]
Hi, 
We read the beacon results with JS and save it to a DB using the before_beacon handler. A minority of our records are showing a bandwidth measurement of 0. What can cause these 0 results? thanks

**Comment by bluesmoon** [comment]
bandwidth measurement does not block the beacon, so it's possible that the beacon is sent before the bandwidth measurement is complete.

**Comment by bluesmoon** [comment]
you can use the `block_beacon` config parameter to change this behaviour: http://www.lognormal.com/boomerang/doc/api/BW.html
