### ISSUE TITLE
Any timeline on when the SPA plugin will be pushed?

### ISSUE THREAD

**Issue by vigneshshanmugam** [lognormal/boomerang#63]
Trying to use some the techniques for SPA's built using React. 

@bluesmoon @nicjansma

**Comment by nicjansma** [comment]
Hi Vignesh,

The beginning parts of it are in `auto_xhr.js`, and we will be publishing plugins that work better with Angular, Backbone and Ember soon.

**Comment by vigneshshanmugam** [comment]
Cool. I am exploring ways of capturing the load time metrics in terms of React App. What do you think  would be the way to start.

**Comment by nicjansma** [comment]
You could experiment with starting listening after React route changes or user interactions by calling `MutationHandler.addEvent` in `auto_xhr.js`.

We'll have full examples for the other SPAs soon.

**Comment by vigneshshanmugam** [comment]
Awesome thanks @nicjansma
