### ISSUE TITLE
Invalid Timing Values

### ISSUE THREAD

**Issue by brianantonelli** [lognormal/boomerang#66]
We're seeing an issue where all of the values from navtiming.js and restiming.js come through as `9999999999999`. Out of 136,793,195 events, there were 94,870 that sent these invalid values. 

Example: 
> ##.##.###.### - - [06/Aug/2015:14:20:57 -0400] "GET /beacon/rum?rt.start=navigation&v=0.9&vis.st=visible&siteVersion=3.125.347009&rt.tstart=1438885256000&rt.cstart=9999999999999&rt.bstart=9999999999999&rt.end=9999999999999&t_done=4897&rt.quit=&nt_red_cnt=0&nt_nav_type=0&nt_nav_st=9999999999999&nt_red_st=0&nt_red_end=0&nt_fet_st=9999999999999&nt_dns_st=9999999999999&nt_dns_end=9999999999999&nt_con_st=9999999999999&nt_con_end=9999999999999&nt_req_st=9999999999999&nt_res_st=9999999999999&nt_res_end=9999999999999&nt_domloading=9999999999999&nt_domint=9999999999999&nt_domcontloaded_st=9999999999999&nt_domcontloaded_end=9999999999999&nt_domcomp=9999999999999&nt_load_st=9999999999999&nt_load_end=9999999999999&nt_unload_st=9999999999999&nt_unload_end=9999999999999&nt_spdy=0&nt_cinf=http%2F1&nt_first_paint=9999999999.334352 HTTP/1.1" 204 - "http://www.XXXXXXXX.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36" "-"

Here's a few of the UAs reporting this issue:
* "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
* "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36"
* "Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG SCH-I545 4G Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/2.1 Chrome/34.0.1847.76 Mobile Safari/537.36"
* "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36"

**Comment by bluesmoon** [comment]
yes, these are bots.  you should drop this traffic.  I've been seeing this since 2011.

**Comment by brianantonelli** [comment]
What gives it away?

**Comment by bluesmoon** [comment]
well, the 99999... values were pretty telling, but I spent a lot of time analysing these, and they were from a relatively small set of IPs when I saw them.

**Comment by brianantonelli** [comment]
I'm analyzing in Kibana now, it looks like you're right. :+1:
