### ISSUE TITLE
When submitting a form via JS, boomerang request opens in new tab

### ISSUE THREAD

**Issue by rswarthout** [lognormal/boomerang#67]
We have run across the issue of when boomerang is configured with the rt and navtiming plugins. When a form on the page is submitted via JS rather than a traditional submit button it opens the boomerang request in a new tab. Is this a known issue?

**Comment by bluesmoon** [comment]
yes, kinda, we've seen something like this and @nicjansma is working on a fix.
can you submit a short test case and Nic will follow up with a fix for you to test.

**Comment by rswarthout** [comment]
The tricky part is that the only time we have seen the ability to reliably reproduce is within an Angular app. I have made a test page that is only the needed pieces but have yet been unable to reproduce on such a simple example. 

For what it is worth, we have also seen this behavior, sporadically, in an non-angular app as well. In the non-angular cases, we have a button that is outside the form. The button is wired up so that on click it submits this the form within the page.

http://www.robertswarthout.com/boomerang/index.html

**Comment by nicjansma** [comment]
Thanks for the test case Robert.  We have a PR incoming that should fix this.  Will followup shortly.

**Comment by nicjansma** [comment]
The most reliable way we've found to send beacons is in this PR: https://github.com/lognormal/boomerang/pull/68

Check out `boomerang.js` `real_sendBeacon`.

We haven't seen any current issues with FORM submissions triggering new tabs with this code.  If you are still able to find a reliable repro, please let us know and we can investigate further.

**Comment by rswarthout** [comment]
We rolled out an update with these changes this morning and all seems good to go. Thanks for the quick response.
