### ISSUE TITLE
Problem setting cookie from beacon in Mobile Safari

### ISSUE THREAD

**Issue by ndimer** [lognormal/boomerang#70]
Hi,

To track session, I return session id in beacon's cookie, so all subsequent requests will be related to the same session.

It works fine in all browsers except Mobile Safari (e.g. Safari on iOS). When I debugged it, I see that cookie is returned by the beacon but Safari ignores it (probably recognized as cross-domain cookie). Is there any workaround or ideas how to solve it?

I am using iframe method to load boomerang script asynchronously. 

Thanks,
Nachum

**Comment by bluesmoon** [comment]
I believe that this is a user preference.  If users do not want to be tracked by 3rd parties, they can disable 3rd party cookies (this is possible in all browsers).  If you own the domain, then you are better off setting the cookie on the main page and just passing it to your beacon collector using `BOOMR.addVar`

**Comment by andreas-marschke** [comment]
@ndimer Can this issue be closed?

**Comment by nicjansma** [comment]
Closing, please re-open if you need additional assistance from us.
