### ISSUE TITLE
Resouce timing plugin

### ISSUE THREAD

**Issue by efpat4** [lognormal/boomerang#72]
Hello everyone,
I'm new to this forum and I've started to use boomerang for performance measurement. At the moment I use the plugins for rt, navtiming and resource timing. While measuring boomerang adds the following data to the url of the beacon: restiming = [object Object] , [object Object] 
 How can I get the original data of the resources from the part of the beacon above? For navtiming and rt plugin boomerang adds normal string values.  Thanks for your help in advance.

**Comment by andreas-marschke** [comment]
Hi @efpat4!

Are you sure that you are seeing `restiming=[object Object]` as _literal string_ or are you seeing restiming with a valid JSON String behind it? 

There is documentation as to what restiming is doing on @nicjansma s blog: 
http://nicj.net/compressing-resourcetiming/

And for a general overview of what ResourceTiming is in practice or how it should work: 
http://nicj.net/resourcetiming-in-practice/

Cheers

Feel free to ask if you have any more questions!

**Comment by bluesmoon** [comment]
I suspect this is because we haven't yet merged in the resource timing changes from #68

**Comment by nicjansma** [comment]
@efpat4 Please see the most recent code, it should have the updated `restiming` parameter.
