### ISSUE TITLE
State of Memory Plugin

### ISSUE THREAD

**Issue by nathagey** [lognormal/boomerang#79]
I can't find docs on the memory plugin, is it production ready?

**Comment by bluesmoon** [comment]
Yes, we've been using it in production for 5 years, but I guess we never ended up documenting it.  Will try and fix that oversight.  For now I'd say just enable it and see what it adds.  There are no configuration options.  It will just try to pull in as much info as it can from the browser.

**Comment by nathagey** [comment]
Awesome. Thanks!
