### ISSUE TITLE
Tips on what to do with the beaconed data

### ISSUE THREAD

**Issue by chmac** [lognormal/boomerang#8]
We've been using boomerang for almost a year now. Gathering tons and tons and tons of juicy data. However, we're yet to produce one single, useful graph from the data. I've tried various approaches, but haven't gotten to anything useful.

As this seems to be the primary support / discussion forum, I'm asking here. Any blog posts out there on what people are doing with boomerang data? Any advice from others using boomerang?

As far as my searching goes, it's either so obvious nobody bothers to write about it, or it's so hard nobody wants to share it, I can't find any info at all. I've even read slides from talks @bluesmoon has given, but couldn't get any concrete suggestions there either. I'd also be grateful for more insight into what the "one number to rule them all" slide means in one of the talks! :-)

**Comment by nicjansma** [comment]
Since this thread has been open a while, and has plenty of good ideas, I'm going to close it.

Here are some additional OS projects that receive Boomerang data:
https://github.com/springernature/boomcatch
https://github.com/andreas-marschke/boomerang-express
