### ISSUE TITLE
boomerang for SPA

### ISSUE THREAD

**Issue by tarun-arya** [lognormal/boomerang#80]
Hi All,
I am trying to use boomerang with a Angular Application.
I have added rt.js, navtiming.js, spa.js and angular.js plugins.
The beacon does not seam to fire. 
What can be the issue ? Is there any detailed documentation for the same ?

Any help would be very useful. Thanks

**Comment by andreas-marschke** [comment]
Hi!

Did you include the boomerang snippet for Angular? We haven't updated the online docs for this yet, but the repository has them at `doc/api/SPA.html`. This should help you integrate Angular and Boomerang better.

Also, how do you init Boomerang in you code? Did you enable the Angular SPA and disabled autorun?

Thanks in advance!

**Comment by tarun-arya** [comment]
Hi Andreas,
Thanks for the response.
I did include the angular snippet.

My Boomerang Init looks something like this : 
BOOMR.init({
    "BW": {
        "enabled": false
    },
    "RT": {
        "session_exp": 1800
    },
    "ResourceTiming": {
        "enabled": true
    },
    "Angular": {
        "enabled": true
    },
    "Ember": {
        "enabled": false
    },
    "Backbone": {
        "enabled": false
    }
});

Any other plugin you see will be required ?
I do not see the beacon being sent still.

Regards,
Tarun

**Comment by tarun-arya** [comment]
I also have autorun : false

**Comment by nicjansma** [comment]
@tarun-arya: Have you included the AngularJS snippet as well?  The boomerang project's documentation needs to be updated but we have the required code examples on http://docs.soasta.com/boomerang/#angularjs

**Comment by tarun-arya** [comment]
Hi @nicjansma yes. I have added the AngularJS snippet and it works fine now. Thank you.
