### ISSUE TITLE
No beacon sent on HTTPS pages

### ISSUE THREAD

**Issue by mayyan** [lognormal/boomerang#82]
When my page is on HTTP, beacon fires as expected at every page load.
But once my page is on HTTPS, no beacon is sent.

My beacon url is to my own server, using relative path, as such:
```
BOOMR.init({
    beacon_url: "/boomerang"
});
```

In browser console, I have this error
`Mixed Content: The page at 'https://......' was loaded over HTTPS, but requested an insecure form action 'http://........./boomerang?rt.start=......'. This request has been blocked; the content must be served over HTTPS.`

What could be the problem?

**Comment by bluesmoon** [comment]
This is strange.  A relative beacon URL should use the protocol of the page.

Which browser are you using?

Also, can you set a breakpoint in `sendData` and inspect the value of `urls` at the top level and `form.action` inside the `submit()` inner function?

Is there a public website where we can see this happening?

**Comment by mayyan** [comment]
I'm using latest Chrome on Mac (Version 49.0.2623.87 (64-bit)), and FireFox 44.0.2 on Mac.

In `sendData()`, `urls` is `["/boomerang"]`.
In `submit()`, `form.action` is `"https://.../boomerang"`
They both look correct to me.

Unfortunately I have not put boomerang on a public site. It is only on my devbox.

**Comment by bluesmoon** [comment]
ok, then I don't understand why you're getting the error since it is submitting to https.  Is your beacon endpoint by any chance redirecting from https to http for the beacon?  Can you look at the chrome web dev network panel and see what happens?

**Comment by mayyan** [comment]
Yes, you are right. It is my server forcing http.
Sorry to bother.

**Comment by bluesmoon** [comment]
No problem May.  Let us know if you have any other issues.
