### ISSUE TITLE
Timing with Chrome

### ISSUE THREAD

**Issue by dugihwsr** [lognormal/boomerang#84]
There is an issue that when running the timing through chrome, you will get extreme results. For example, you will get timing of 17+ minutes to load a page but then get 800ms, then randomly 29 minutes. Doesn't seem to happen in IE for Firefox.

**Comment by bluesmoon** [comment]
can you show us an example page where you see this behaviour?

**Comment by dugihwsr** [comment]
hopefully this comes across ok. In column order you ahve time/perceived load time/platform/browser/version of browser

4/9 15:37		39.1K	Windows	Chrome	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
4/9 15:38		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:38		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:38		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:38		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:38		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:38		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		2.0K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		1.8K	Windows	Chrome	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
4/9 15:35		1.3K	Windows	Firefox	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0
4/9 15:36		1.1K	Windows	Chrome	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
4/9 15:36		920.0	Windows	Chrome	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
4/9 15:36		839.0	Windows	Chrome	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
4/9 15:36		826.0	Windows	Chrome	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36

**Comment by bluesmoon** [comment]
Make sure you're looking at the page load beacon and not the unload beacon.

**Comment by dugihwsr** [comment]
here is the boomerang payload or one with a "perceived load time of 34.7
seconds" but actually took less than a MS.

DVA_Appliance: Boomerang beacon parameters: {
    "rt.start": "navigation",
    "u": "http://server/home/thirdpage.html",
    "v": "0.9",
    "vis.st": "visible",
    "ua.plt": "Win32",
    "ua.vnd": "Google Inc.",
    "nu": "http://server/home/index.html",
    "nt_red_cnt": "0",
    "nt_nav_type": "0",
    "nt_nav_st": "1460479761821",
    "nt_red_st": "0",
    "nt_red_end": "0",
    "nt_fet_st": "1460479761822",
    "nt_dns_st": "1460479761822",
    "nt_dns_end": "1460479761822",
    "nt_con_st": "1460479761822",
    "nt_con_end": "1460479761822",
    "nt_req_st": "1460479761825",
    "nt_res_st": "1460479761825",
    "nt_res_end": "1460479761828",
    "nt_domloading": "1460479761845",
    "nt_domint": "1460479761866",
    "nt_domcontloaded_st": "1460479761866",
    "nt_domcontloaded_end": "1460479761867",
    "nt_domcomp": "1460479762102",
    "nt_load_st": "1460479762102",
    "nt_load_end": "1460479762102",
    "nt_unload_st": "1460479761832",
    "nt_unload_end": "1460479761832",
    "nt_spdy": "0",
    "nt_cinf": "http/1",
    "nt_first_paint": "1460479761.846362",
    "rt.tstart": "1460479761821",
    "rt.cstart": "1460479761820",
    "rt.bstart": "1460479761861",
    "rt.end": "1460479796522",
    "t_done": "34701",
    "r": "http://server/home/secondpage.html",
    "rt.quit": "",
    "vis.lv": "1144",
    "vis.lh": "33891"

On Mon, Apr 11, 2016 at 7:29 PM, Philip Tellis <notifications@github.com>
wrote:

> Make sure you're looking at the page load beacon and not the unload beacon.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lognormal/boomerang/issues/84#issuecomment-208672518>
>



-- 
Jeremy

"Success is the ability to make wise decisions."
                                        - Anonymous

**Comment by bluesmoon** [comment]
This is an `unload` beacon.  You can tell because `rt.quit` is present on the beacon.  This is telling you when the page unloaded (ie, browser closed), not when the page loaded.  You should look for beacons where `rt.quit` is absent which indicates a `load` beacon.

**Comment by dugihwsr** [comment]
what does the t_done represent? We are extracting the t_done to get the
perceived load time of user.

On Tue, Apr 12, 2016 at 9:58 AM, Philip Tellis <notifications@github.com>
wrote:

> This is an unload beacon. You can tell because rt.quit is present on the
> beacon. This is telling you when the page unloaded (ie, browser closed),
> not when the page loaded. You should look for beacons where rt.quit is
> absent which indicates a load beacon.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lognormal/boomerang/issues/84#issuecomment-209007172>
>



-- 
Jeremy

"Success is the ability to make wise decisions."
                                        - Anonymous

**Comment by bluesmoon** [comment]
`t_done` is what you want, but not from this beacon.  You need the `t_done` value from the load beacon, and you are looking at the unload beacon.  Please look at the correct beacon.

**Comment by bluesmoon** [comment]
In other words, ignore all beacons where `rt.quit` is present.  It is only relevant when doing session duration analysis.

**Comment by dugihwsr** [comment]
awesome! i will make the adjustment. thank you phillip.

On Tue, Apr 12, 2016 at 10:12 AM, Philip Tellis <notifications@github.com>
wrote:

> t_done is what you want, but not from this beacon. You need the t_done
> value from the load beacon, and you are looking at the unload beacon.
> Please look at the correct beacon.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lognormal/boomerang/issues/84#issuecomment-209011845>
>



-- 
Jeremy

"Success is the ability to make wise decisions."
                                        - Anonymous

**Comment by dugihwsr** [comment]
off question, do you know why this would only be showing itself in chrome?

**Comment by bluesmoon** [comment]
it's happening in all browsers (it's designed to do that), just that with other browsers the beacon is probably getting lost (ie, the browser might be aborting the network connection since it is shutting down).  You will probably see it in 20% or less of all page views.

**Comment by dugihwsr** [comment]
Makes sense.  Thank you again.
